version: "1"
rules:
  - base: main
    upstream: KelvinTegelaar:main
    mergeMethod: merge
  - base: dev
    upstream: KelvinTegelaar:dev
    mergeMethod: merge
  - base: website
    upstream: KelvinTegelaar:website
    mergeMethod: merge
  - base: docs
    upstream: KelvinTegelaar:docs
    mergeMethod: merge
  - base: release/beta
    upstream: KelvinTegelaar:release/beta
    mergeMethod: merge
  - base: release/nightly
    upstream: KelvinTegelaar:release/nightly
    mergeMethod: merge
